version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=your_secret_key_here
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DATABASE_URL=postgres://blooddonation:blooddonation@db:5432/blooddonation
      - EMAIL_HOST=your_email_host
      - EMAIL_PORT=your_email_port
      - EMAIL_HOST_USER=your_email_user
      - EMAIL_HOST_PASSWORD=your_email_password
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=blooddonation
      - POSTGRES_USER=blooddonation
      - POSTGRES_PASSWORD=blooddonation

volumes:
  postgres_data: